In [1]:
#Importing library that will be used
import numpy as np
from fractions import Fraction as frac

In [16]:
#Function to calculate the inverse of a matrix
def inverse(A):
    print ('Nossa matriz original A:\n',A)
    
    #Using the function np.linal.inv(x) to find the inverse.
    A_inverse = np.linalg.inv(A)
    #print (A_inverse)
    #Printing the matrix transofrtming decimal numbers into fractions
    for i in range(2):
        for j in range(2):
            A_inverse[i][j]=frac(A_inverse[i][j])
    print('\nMatriz inversa A(-1):\n',A_inverse)
    #Finding the inverse of A(-1)
    A_inverse = np.linalg.inv(A_inverse)
    print('O inverso de A(-1): \n', A_inverse)
    # E find the original matrix here

In [17]:
#Instantiating the matrix
A = np.array([[1,1,1],[2,1,4],[2,3,5]])

inverse(A)

# Na matriz exemplo do arquivo envado pelo professor o código do matlab faz a inversão da matriz olhando para a matriz identidade.

Nossa matriz original A:
 [[1 1 1]
 [2 1 4]
 [2 3 5]]

Matriz inversa A(-1):
 [[ 1.4  0.4 -0.6]
 [ 0.4 -0.6  0.4]
 [-0.8  0.2  0.2]]
O inverso de A(-1): 
 [[1. 1. 1.]
 [2. 1. 4.]
 [2. 3. 5.]]
